### ISSUE TITLE
깃 커밋 내역 정리

### ISSUE THREAD

**Issue by badaclockA** [nakyeonko3/devcamp-onboarding-04#9]
## TODO
- [x] 커밋 내용 합치기
- [x] 커밋 메시지 내용 수정

## 현재 문제점 
- 현재 커밋내역이 30개 이상을 넘어감.
- 커밋 내역을 통해 이게 무엇이 변경된 것인지 알기 어려움, 커밋 메시지가 구체적이지 않음,
- 변경된 커밋 내용들을 정리해서 한눈에 알아보기 힘듬
- 의미 없는 커밋 내역들이 많음, 단순 오탈자 수정, 마크다운 문법 오류 수정등

## 개선할 내용
- 의미없는 커밋 내역을 다른 커밋과 합치기
- 커밋 메시지를 구체적인 내용으로 변경

## 커밋 메시지 컨벤션 
 아래의 형식대로 커밋 내용 작성을 권장
 - 커밋 메시지 형식
 ```
 변경한 문서내용 > 구체적으로 어떤 내용이 변경되었는지 적기
 ```
- 커밋 메시지 예시
 ```
 Update 기능정의서.md  > 기능정의서에 유저플로우 다이어그램이 추가
 ```

**Comment by nakyeonko3** [comment]
- [ ] 커밋 내용 합치기
- [ ] 커밋 메시지 내용 수정

**Comment by badaclockA** [comment]
의견 있으시면 누구나여기에 코멘트 달아주세요.

**Comment by badaclockA** [comment]
## 커밋 내역 합치는 방법, 커밋 메시지 수정 방법
`Claude`라는 AI의 답변임

최근 커밋들이 아닌 이전 커밋들을 합치고 싶다면 조금 다른 방식으로 진행해야 합니다. 

1. **대화형 rebase 시작하기**

```
git rebase -i --root
```

이 명령어를 실행하면 전체 커밋 로그가 열립니다.

2. **커밋 목록에서 합치고자 하는 커밋들 찾기**

텍스트 에디터에서 합치고자 하는 커밋들을 찾습니다. 가장 오래된 커밋부터 시작해서 `pick`을 `squash`(또는 `s`)로 변경합니다. 가장 최신 커밋의 `pick`은 그대로 둡니다.

3. **커밋 메시지 수정하기**

파일을 저장하고 텍스트 에디터를 종료하면 다른 텍스트 에디터가 열립니다. 여기에서 새로운 커밋 메시지를 작성할 수 있습니다.

4. **rebase 완료하기**

새로운 커밋 메시지를 작성하고 텍스트 에디터를 종료하면 rebase가 완료됩니다. 이제 `git log`를 실행하면 선택한 이전 커밋들이 하나의 커밋으로 합쳐진 것을 확인할 수 있습니다.

이 방법을 사용하면 최근 커밋들이 아닌 원하는 이전 커밋들을 선택하여 합칠 수 있습니다. 단, 여전히 공유 저장소에 Push된 커밋들은 rebase하면 안 된다는 점을 주의해야 합니다.
